### ISSUE TITLE
passing #ocr a binary image file results in error

### ISSUE THREAD

**Issue by jspillers** [Yeti-Media/rubix-ruby#5]
the following call to the API:

```
filename = '/path/to/an/image.jpg'
client.ocr(file: File.binread(filename))
```

results in the following error:

```
/Users/<user>/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubix-api-0.0.2/lib/rubix.rb:91:in `process_reponse': Rubix::ServerError (Rubix::ServerError)
    from /Users/<user>/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubix-api-0.0.2/lib/rubix.rb:66:in `block in ocr'
    from /Users/<user>/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubix-api-0.0.2/lib/rubix.rb:74:in `error_handler'
    from /Users/<user>/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubix-api-0.0.2/lib/rubix.rb:64:in `ocr'
    from test_rubix_api.rb:18:in `block in <main>'
    from test_rubix_api.rb:15:in `each'
    from test_rubix_api.rb:15:in `<main>'
```

**Comment by ntreadway** [comment]
@jspillers Thanks for you help detecting these issues. The project as been on hold while we build a new team. In the short term we have recently made improvements to the OCR API but as you can see this SDK needs to be updated. We are in the process of looking for a part time dev to help out with this project.
